#!/usr/bin/env bash
[[ "${DOCLI_DEBUG:-off}" == "on" ]]       && set -exo pipefail || set -eo pipefail
[[ "${DOCLI_UNSET_VARS:-off}" == "on" ]]  && set -u
############################################################################### #dltbr
#              https://DevOps.click - DevOps taken seriously                  # #dltbr
###############################################################################

## DOCLI MODULE INFORMATION
DOCLI_MODULE_VERSION="0.0.01"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE="$(basename "${BASH_SOURCE[0]}")"                                             || DOCLI_MODULE="$(basename "$0")"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE_TYPE="$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"             || DOCLI_MODULE_TYPE="$(basename "$(dirname "$(realpath "$0")")")"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE_UPPER=$(echo "$(basename "${BASH_SOURCE[0]}")"  | tr '[:lower:]' '[:upper:]') || DOCLI_MODULE_UPPER=$(echo "$(basename "$0")" | tr '[:lower:]' '[:upper:]')
##[[ "${DOCLI_MODULE_ARRAY_SOURCE:-on}" == "on" ]] && source ${DOCLI_DIR:-$DOCLI}/functions/docli_module_array

## VERBOSE INFORMATION
[[ "${DOCLI_VERBOSE:-off}" == "on" ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"

# TODO: Functions to generate single files like it is now, but also generate all files from folders that it encounter #:: text on it!

# Header section to be added at the top of the markdown file
header='
<!-- markdownlint-disable -->
v1
<!-- markdownlint-restore -->

<!--Way1 Best https://badgen.net -->
<p align="center">
 <img width="50px" src="https://s3.amazonaws.com/devops.public/icons/icons-work/terminal_02.png" align="center" alt="GitHub Readme Stats" />
 <h2 align="center">DevOps.click CLI</h2>
 <p align="center">DevOps taken seriously!</p>
</p>
  <p align="center">
    <!-- <a href="https://github.com/devops-click/docli/actions">
      <img alt="Tests Passing" src="https://github.com/devops-click/docli/workflows/Test/badge.svg" />
    </a> -->
    <a href="https://github.com/anfergainst/test/releases/latest">
    <img alt="Latest Release" src="https://badgen.net/github/release/devops-click/docli">
    </a>
    <a href="https://github.com/anfergainst/test/releases/latest">
    <img alt="Website Status" src="https://img.shields.io/website-up-down-green-red/https/devops.click">
    </a>
    <a href="https://github.com/devops-click/docli/graphs/contributors">
    <img alt="GitHub followers" src="https://img.shields.io/github/followers/devops-click">
    </a>
    <a href="https://github.com/devops-click/docli/issues">
      <img alt="Issues" src="https://img.shields.io/github/issues/devops-click/docli?color=0088ff" />
    </a>
    <a href="https://github.com/devops-click/docli/pulls">
      <img alt="GitHub pull requests" src="https://img.shields.io/github/issues-pr/devops-click/docli?color=0088ff" />
    </a>
    <!-- OSSF Installation and Configuration - https://github.com/ossf/scorecard-action/tree/dd5015aaf9688596b0e6d11e7f24fff566aa366b#authentication-with-pat -->
    <a href="https://securityscorecards.dev/viewer/?uri=github.com/devops-click/docli">
      <img alt="OpenSSF Scorecard" src="https://api.securityscorecards.dev/projects/github.com/devops-click/docli/badge" />
    </a>
    <br />
  </p>

  <p align="center">
    <a href="#documentation">Documentation</a>
    ·
    <a href="https://github.com/devops-click/docli/issues/new/choose">Report Bug</a>
    ·
    <a href="https://github.com/devops-click/docli/issues/new/choose">Request Feature</a>
    ·
    <a href="https://github.com/devops-click/docli/discussions/1770">FAQ</a>
    ·
    <a href="https://github.com/devops-click/docli/discussions">Ask Question</a>
  </p>
  <p align="center">
    <a href="/docs/readme_fr.md">Français </a>
    ·
    <a href="/docs/readme_cn.md">简体中文</a>
    ·
    <a href="/docs/readme_es.md">Español</a>
    ·
    <a href="/docs/readme_de.md">Deutsch</a>
    ·
    <a href="/docs/readme_ja.md">日本語</a>
    ·
    <a href="/docs/readme_pt-BR.md">Português Brasileiro</a>
    ·
    <a href="/docs/readme_it.md">Italiano</a>
    ·
    <a href="/docs/readme_kr.md">한국어</a>
    ·
    <a href="/docs/readme_nl.md">Nederlands</a>
    ·
    <a href="/docs/readme_np.md">नेपाली</a>
    ·
    <a href="/docs/readme_tr.md">Türkçe</a>
  </p>
</p>

<p align="center">Please note that documentation translations may be outdated, try to use english documentation if possible.</p>

<p align="center">Support the project! Consider <a href="https://www.paypal.com/donate/?business=G37WGAZPY8XCC&no_recurring=0&item_name=https%3A%2F%2Fdevops.click+-+%0AContribute+to+our+community+and+help+us+keep+growing%21&currency_code=EUR">donating</a> to help it improve!</p>

</p>

# Features <!-- omit in toc -->

<!--Way1 Best https://github.com/badges/shields -->
<!-- [![Website Status](https://img.shields.io/website-up-down-green-red/https/devops.click)](https://github.com/devops-click) -->
<!--Way2 Worst-->
<!-- [![Website Status](https://img.shields.io/website.svg?down_color=red&down_message=down&up_color=green&up_message=up&url=http%3A%2F%2Fdevops.click)](https://devops.click) -->
<!-- markdownlint-restore -->

<a href="https://devops.click">
  <img height=200 align="center" src="https://github-readme-stats.vercel.app/api?username=anfergainst" />
</a>
<a href="https://devops.click">
  <img height=200 align="center" src="https://github-readme-stats.vercel.app/api/top-langs?username=anfergainst&layout=compact&langs_count=8&card_width=320" />
</a>

<!--[![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/andersonayres/)
[![WHATSAPP](https://img.shields.io/badge/WhatsApp-25D366?style=for-the-badge&logo=whatsapp&logoColor=white)](https://web.whatsapp.com/+351910628445)
[![TELEGRAM](	https://img.shields.io/badge/Telegram-2CA5E0?style=for-the-badge&logo=telegram&logoColor=white)](https://web.telegram.org/z/+351910628445)-->
[![FACEBOOK](https://img.shields.io/badge/Facebook-1877F2?style=for-the-badge&logo=facebook&logoColor=white)](https://www.facebook.com/devops.click)
[![INSTAGRAM](https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white)](https://www.instagram.com/devops.click/)
[![INSTAGRAM](https://img.shields.io/badge/terraform-%235835CC.svg?style=for-the-badge&logo=terraform&logoColor=white)](https://devops.click/)
[![Slack Community](https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white)](https://devops.click)


<!--https://github.com/devops-click/docli-->
<!-- [![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra&layout=donut-vertical)](https://github.com/devops-click/docli) -->
<!-- ![Anderson Ayres GitHub stats](https://github-readme-stats.vercel.app/api?username=anfergainst&show_icons=true&theme=dracula) -->


<!-- <div style="display:inline_block"><br/>
    <img align="center" alt="html5" src="https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white"/>
    <img align="center" alt="html5" src="https://img.shields.io/badge/CSS-239120?&style=for-the-badge&logo=css3&logoColor=white"/>
    <img align="center" alt="html5" src="https://img.shields.io/badge/JavaScript-323330?style=for-the-badge&logo=javascript&logoColor=F7DF1E"/>
</div> -->

<!-- [![README Header][readme_header_img]][readme_header_link] -->


# File Documentation

---

'

# Footer section to be added at the bottom of the markdown file
footer="
---

# TODO: Remove hours from date.
Generated using the \`docli gendoc\` on $(date)
"

# Check if a filename has been provided
if [ -z "$1" ]; then
    echo "Usage: $0 <filename>"
    exit 1
fi

# Check if the file exists
if [ ! -f "$1" ]; then
    echo "File not found: $1"
    exit 1
fi

# Create or overwrite the output markdown file
output_file="${1%.*}.md"

# Write the header section
echo "$header" > "$output_file"

# Extract lines starting with "#::" and append to the markdown file
grep '^#:: ' "$1" | sed 's/^#:: //' >> "$output_file"

# Append the footer section
echo "$footer" >> "$output_file"

echo "Markdown file has been generated."
