#!/usr/bin/env bash
[[ "${DOCLI_DEBUG:-off}" == "on" ]]       && set -exo pipefail || set -eo pipefail
[[ "${DOCLI_UNSET_VARS:-off}" == "on" ]]  && set -u
############################################################################### #dltbr
#              https://DevOps.click - DevOps taken seriously                  # #dltbr
###############################################################################
#                           docli K8S Namespace Tools
###############################################################################

## DOCLI MODULE INFORMATION
[[ "${BASH_SOURCE[0]}" != "" ]] && REAL_PATH=$(realpath "${BASH_SOURCE[0]}") || REAL_PATH=$(realpath "$0")
DOCLI_MODULE_VERSION=0.0.01
DOCLI_MODULE="$(basename "${BASH_SOURCE[0]}")"
DOCLI_MODULE_TYPE="$(basename "$(dirname "$($REAL_PATH)")")"
DOCLI_MODULE_UPPER=$(echo "$DOCLI_MODULE" | tr '[:lower:]' '[:upper:]')

## VERBOSE INFORMATION
[[ "${DOCLI_VERBOSE:-off}" == "on" ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"

c_nsp=$1
c_file=tmp-ns.json

echo "** Checking all locking objects for namespace $c_nsp"
kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found -n $c_nsp

kubectl get namespace $c_nsp -o json >$c_file
echo "** Now, edit the following file: $file and remove "kubernetes" from the "finalizers:" **"
echo "** After editing, run the following to start a proxy and then issue the command to delete: **"
echo "kubectl proxy"
echo "curl -k -H "Content-Type: application/json" -X PUT --data-binary @$file http://127.0.0.1:8001/api/v1/namespaces/$c_nsp/finalize"
echo "rm -rf tmp-ns.json"
