#!/bin/bash -euo pipefail

environments=("fin" "sec" "ent" "prd" "stg" "qas" "dev" "val")

for environment in "${environments[@]}"; do
    echo "Running command for environment: $environment"
    ./run "$environment"
done