#!/usr/bin/env bash
## !! SHOULD NOT HAVE ANY SET FOR SHELL HERE !! #
############################################################################### #dltbr
#              https://DevOps.click - DevOps taken seriously                  # #dltbr
###############################################################################

## DOCLI MODULE INFORMATION
DOCLI_MODULE_VERSION="0.0.01"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE="$(basename "${BASH_SOURCE[0]}")"                                             || DOCLI_MODULE="$(basename "$0")"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE_TYPE="$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"             || DOCLI_MODULE_TYPE="$(basename "$(dirname "$(realpath "$0")")")"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE_UPPER=$(echo "$(basename "${BASH_SOURCE[0]}")"  | tr '[:lower:]' '[:upper:]') || DOCLI_MODULE_UPPER=$(echo "$(basename "$0")" | tr '[:lower:]' '[:upper:]')
##[[ "${DOCLI_MODULE_ARRAY_SOURCE:-on}" == "on" ]] && source ${DOCLI_DIR:-$DOCLI}/functions/docli_module_array

## VERBOSE INFORMATION
[[ "${DOCLI_VERBOSE:-off}" == "on" ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"

# Prevents script from being called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "* $DOCLI_MODULE: This module cannot be called directly! Exiting... *"
  exit 1
fi

# Source this file and use as instructed bellow:
# Usage Example:
# FILE_OR_DIR_CHECK=(
#     ~/devops/scripts/set-bash-colors-tput.sh
#     ~/devops/envs
#     $script_dir/../devops/.functions/bash_terraform
#     $script_dir/../devops/.functions/bash_gpg_key
# )
# source_files_list

function source_files_list_dir_check {
  # Iterate through the sources and source or check them
  for source in "${FILE_OR_DIR_CHECK[@]}"; do
    if [[ -f $source ]]; then
      echo "** Sourcing file: $source"
      source $source
    elif [[ -d $source ]]; then
      echo "** Directory found: $source"
    else
      echo "ERROR: $source not found. Please execute the basic setup before proceeding."
      exit 1
    fi
  done
}
