#!/usr/bin/env bash
############################################################################### #dltbr
#              https://DevOps.click - DevOps taken seriously                  # #dltbr
###############################################################################
#                             docli pre-env script
###############################################################################
#-----------------------------------------------------------------------------;
#                                PRE ENV SCRIPT                               |
#-----------------------------------------------------------------------------'
# Component to be loaded by all docli modules

## DOCLI MODULE INFORMATION
DOCLI_MODULE=docli_pre_envs
DOCLI_MODULE_TYPE=functions
DOCLI_MODULE_VERSION=0.0.5
DOCLI_MODULE_UPPER=$(echo "$DOCLI_MODULE" | tr '[:lower:]' '[:upper:]')
REAL_PATH=$(realpath "${BASH_SOURCE[0]}")

echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****"
echo -e "***** $REAL_PATH *****\n"

source $DOCLI/.docli_envs

############################################
# AUTO-UPDATER - docli
############################################
# docli MAIN Installer - Define the URL and the destination path
INSTALLER_LOCAL_VERSION=$(cat $DOCLI_DIR/.version || echo "0.0.0")
INSTALLER_REMOTE_VERSION=$(curl -s https://raw.githubusercontent.com/devops-click/docli/main/.devops/.version)
INSTALLER_COMMAND="$DOCLI_DIR/bin/docli -um"
INSTALLER_MODULE="$DOCLI_MODULE"

# Sourcing bash_basic_functions only after defining the INSTALLER_MODULE variable, otherwise it get's overwritten.
source $DOCLI_DIR/functions/bash_basic_functions

echo "* docli_pre_envs: calling check_new_versions *"
run_once "$INSTALLER_MODULE" "check_new_versions docli $INSTALLER_LOCAL_VERSION $INSTALLER_REMOTE_VERSION \"$INSTALLER_COMMAND\""
############################################