#!/usr/bin/env bash
## Atutomatically export variables to scripts calling it
set -a
DOCLI_MODULE_ARRAY_SOURCE="off" # Keep disabled to avoid loops
############################################################################### #dltbr
#              https://DevOps.click - DevOps taken seriously                  # #dltbr
###############################################################################
#                             docli pre-env script
###############################################################################
#-----------------------------------------------------------------------------;
#                                PRE ENVS SCRIPT                              |
#-----------------------------------------------------------------------------'
# Component to be loaded by all docli modules that calls docli_pre_envs

## DOCLI MODULE INFORMATION
DOCLI_MODULE_VERSION="0.0.01"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE="$(basename "${BASH_SOURCE[0]}")"                                             || DOCLI_MODULE="$(basename "$0")"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE_TYPE="$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"             || DOCLI_MODULE_TYPE="$(basename "$(dirname "$(realpath "$0")")")"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE_UPPER=$(echo "$(basename "${BASH_SOURCE[0]}")"  | tr '[:lower:]' '[:upper:]') || DOCLI_MODULE_UPPER=$(echo "$(basename "$0")" | tr '[:lower:]' '[:upper:]')
[[ "${DOCLI_MODULE_ARRAY_SOURCE:-on}" == "on" ]] && source ${DOCLI_DIR:-$DOCLI}/functions/docli_module_array

## VERBOSE INFORMATION
[[ "${DOCLI_VERBOSE:-off}" == "on" ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"

# Prevents script from being called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "* $DOCLI_MODULE: This module cannot be called directly! Exiting... *"
  exit 1
fi
############################################
# DEVELOPER MODE
############################################
: "${DOCLI:=$HOME/devops}"
: "${DOCLI_DEVELOPER_MODE:=false}"
: "${DOCLI_REPOSITORY:-$HOME/GitHub/docli}"

if [[ $DOCLI_DEVELOPER_MODE == true ]]; then
  [[ "${DOCLI_VERBOSE:-off}" == "on" && ${DOCLI_DEBUG:-false} == "true" ]] && echo -e "* $DOCLI_MODULE: DEVELOPER_MODE ONNN *"
  export DOCLI_DIR="${DOCLI_REPOSITORY}/.devops"
else
  export DOCLI_DIR=$DOCLI
fi

# Set the right /bin path after determine if Developer Mode is on or off
PATH="$PATH:$DOCLI_DIR/bin:/opt/homebrew/bin"
############################################

# source $DOCLI_DIR/functions/bash_basic_functions
# docli_params_load

[[ "${DOCLI_VERBOSE:-off}" == "on" ]] && echo "* Sourcing: $DOCLI_DIR/functions/x_docli_pre_envs"
# [[ "${DOCLI_MODULE_ARRAY_PRE_ENVS_SOURCE:-on}" == "on" ]] && source $DOCLI_DIR/functions/x_docli_pre_envs "$@"
source $DOCLI_DIR/functions/x_docli_pre_envs "$@"
