#!/usr/bin/env bash
## !! SHOULD NOT HAVE ANY SET FOR SHELL HERE !! #
############################################################################### #dltbr
#              https://DevOps.click - DevOps taken seriously                  # #dltbr
###############################################################################
# PS: This script is intended to be used as source for others.
# runtf call script, to be sourced directly from terraform/deploy/recipe folders
# by ./runtf script, with or without parameters.
###############################################################################
# If variable DOCLI_PROJECT_CLIENT is set, the last option will be set by default
# -----------------------------------------------------------------------------
# -f|--force   <-   runs terraform without asking (can be set anywhere in the arg position)
# -----------------------------------------------------------------------------
# Examples:
# runtf
# runtf -force (runs terraform without asking)
# runtf aws-sso apply ent usw2 (when variable is already set)
# runtf aws-sso apply ent usw2 "do" -force (no ask + when variable is not set)
###############################################################################

## DOCLI MODULE INFORMATION
DOCLI_MODULE_VERSION="0.0.01"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE="$(basename "${BASH_SOURCE[0]}")"                                             || DOCLI_MODULE="$(basename "$0")"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE_TYPE="$(basename "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")"             || DOCLI_MODULE_TYPE="$(basename "$(dirname "$(realpath "$0")")")"
[[ "${BASH_SOURCE[0]}" != "" ]] && DOCLI_MODULE_UPPER=$(echo "$(basename "${BASH_SOURCE[0]}")"  | tr '[:lower:]' '[:upper:]') || DOCLI_MODULE_UPPER=$(echo "$(basename "$0")" | tr '[:lower:]' '[:upper:]')
##[[ "${DOCLI_MODULE_ARRAY_SOURCE:-on}" == "on" ]] && source ${DOCLI_DIR:-$DOCLI}/functions/docli_module_array

## VERBOSE INFORMATION
[[ "${DOCLI_VERBOSE:-off}" == "on" ]] && echo -e "\n***** $DOCLI_MODULE version $DOCLI_MODULE_VERSION ($DOCLI_MODULE_TYPE) *****\n"

# Prevents script from being called directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "* $DOCLI_MODULE: This module cannot be called directly! Exiting... *"
  exit 1
fi

PATH="${DOCLI_DIR:-/opt/devops}/bin:/opt/homebrew/bin:/usr/sbin:/sbin:/usr/bin:/bin:/usr/local/bin:/usr/local/sbin:$HOME/devops/bin:$PATH"

export DOCLI_PARAM_OPTIONS=("apply" "apply_unlock" "apply_force" "destroy" "destroy_force" "plan" "plan_destroy" "show" "apply_plan" "refresh" "state_list" "state_pull" "state_show" "import" "providers" "output_base64")

# Check if the array is already initialized and has at least one element
if [ -z "${DOCLI_PARAM_SKIP_BASEDIR_ENV_LOAD+x}" ] || [ ${#DOCLI_PARAM_SKIP_BASEDIR_ENV_LOAD[@]} -eq 0 ]; then
  DOCLI_PARAM_SKIP_BASEDIR_ENV_LOAD=("backup" "backup-tag-existing")
  DOCLI_PARAM_SKIP_BASEDIR_ENV_LOAD_STR="${DOCLI_PARAM_SKIP_BASEDIR_ENV_LOAD[*]}"
  export DOCLI_PARAM_SKIP_BASEDIR_ENV_LOAD_STR
fi

export DOCLI_PARAM_MODULE=${DOCLI_PARAM_MODULE:-terraform}

[[ -z $DOCLI_PARAM_FORCE ]] && tf_force_param=0 || tf_force_param=$DOCLI_PARAM_FORCE
args=()

###############################################################
# runtf pre-hook
# OPTIONAL -> Runs only if file exists
###############################################################
# Calling folder pre-hook (terraform/cloud/deploy/recipe)
if [[ -f .docli_pre_hook ]]; then
  echo "* Current folder .docli_pre_hook found. Using it. *"
  source .docli_pre_hook "${args[@]}"
fi
# Cloud Terraform pre-hook (applies to all TFs inside that specific Cloud if file found)
if [[ -f $DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/.docli_pre_hook ]]; then
  echo "* Cloud Terraform .docli_pre_hook found for the project. Using it. *"
  source $DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/.docli_pre_hook "${args[@]}"
fi
# General Terraform pre-hook (applies to all TFs if file found)
if [[ -f $DOCLI_PROJECT_ROOT/terraform/.docli_pre_hook ]]; then
  echo "* General Terraform .docli_pre_hook found for the project. Using it. *"
  source $DOCLI_PROJECT_ROOT/terraform/.docli_pre_hook "${args[@]}"
fi
###############################################################

# Check if any arguments are passed
if [ $# -eq 0 ]; then
  default_tf_command=apply
else
  # Process arguments to check for -force and remove it
  for arg in "$@"; do
    if [ "$arg" = "-force" ] || [ "$arg" = "--force" ]; then
      echo $arg
      tf_force_param=1
      default_tf_command=apply_force
    else
      args+=("$arg")  # Add argument to new array if it's not -force
    fi
  done
fi

########## EMPTY
# Check if arguments are empty (excludes -force)
if [ ${#args[@]} -eq 0 ]; then
  echo "runtf_call -> empty params"
  # source $DOCLI_DIR/bin/runtf "${args[@]}"
  # Iterate through env_list
  for env in "${env_list[@]}"; do
    # Iterate through reg_list
    for region in "${reg_list[@]}"; do
      # Check if the env is enabled for the current region
      enabled_var="enabled_${region}[@]"
      if [[ " ${!enabled_var} " =~ " ${env} " ]]; then

        echo -e "\n######################################################################################"
        echo -e " => runtf_call - Calling docli runtf script for Terraform"
        echo -e "######################################################################################"
        echo -e " Force Option: $(if [ "$tf_force_param" -eq 1 ]; then echo "YES (FORCED OPTION SELECTED !!!!!)"; else echo "no"; fi)"
        echo -e "######################################################################################"
        echo -e " Cloud Type:   $DOCLI_PARAM_CLOUD"
        echo -e " Environment:  $env"
        echo -e " Short Region: $region"
        echo -e "######################################################################################"
        echo -e "                         DOCLI Environment Variables"
        env | grep "DOCLI_*"
        echo -e "######################################################################################"

        if [ $tf_force_param -eq 1 ]; then
          source $DOCLI_DIR/bin/runtf "--cloud=$DOCLI_PARAM_CLOUD" "$default_tf_command" "--env=$env" "--short-region=${region}" --force
        else
          source $DOCLI_DIR/bin/runtf "--cloud=$DOCLI_PARAM_CLOUD" "$default_tf_command" "--env=$env" "--short-region=${region}"
        fi

      else
        echo "Skipping env: $env for short_region: $region"
      fi
    done
  done

# Check if force flag is set and modify 'apply' to 'apply_force'
elif [ ${#args[@]} != 0 ] && [ $tf_force_param -eq 1 ]; then
  echo "** arguments passed: running TF with -force flag!"
  for i in "${!args[@]}"; do
    echo "argument_count=$i"
    if [ "${args[$i]}" = "apply" ]; then
      args[$i]="apply_force"
      echo "argument=${args[$i]}"
    elif [ "${args[$i]}" = "destroy" ]; then
      args[$i]="destroy_force"
      echo "argument=${args[$i]}"
    else
      echo "argument=${args[$i]}"
    fi
  done
  # Now run the command with modified arguments
  echo "force all params: $@"
  echo "force all args:   ${args[@]}"
  source $DOCLI_DIR/bin/runtf "${args[@]}"

elif [ ${#args[@]} != 0 ] && [ $tf_force_param -eq 0 ]; then
  echo "** arguments passed: running normal TF..."
  echo "no-force all params: $@"
  echo "no-force all args:   ${args[@]}"
  source $DOCLI_DIR/bin/runtf "${args[@]}"
fi

###############################################################
# runtf post-hook
# OPTIONAL -> Runs only if file exists
###############################################################
# Calling folder post-hook (terraform/cloud/deploy/recipe)
if [[ -f .docli_post_hook ]]; then
  echo "* Current folder .docli_post_hook found. Using it. *"
  source .docli_post_hook "${args[@]}"
fi
# Cloud Terraform post-hook (applies to all TFs inside that specific Cloud if file found)
if [[ -f $DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/.docli_post_hook ]]; then
  echo "* Cloud Terraform .docli_post_hook found for the project. Using it. *"
  source $DOCLI_PROJECT_ROOT/terraform/$DOCLI_PARAM_CLOUD/.docli_post_hook "${args[@]}"
fi
# General Terraform post-hook (applies to all TFs if file found)
if [[ -f $DOCLI_PROJECT_ROOT/terraform/.docli_post_hook ]]; then
  echo "* General Terraform .docli_post_hook found for the project. Using it. *"
  source $DOCLI_PROJECT_ROOT/terraform/.docli_post_hook "${args[@]}"
fi
###############################################################
